image: docker:latest
services:
  - docker:dind
variables:
  DOCKER_DRIVER: overlay2

stages:
  - build

.build_template: &build_definition
  stage: build
  only:
    refs:
      - branches
      - /^v(?:\d+\.)+\d+$/
    variables:
      - $VARIANT_TAG
      - $VARIANT_TAG_WITH_VERSION
      - $VARIANT_BUILD_DIR
  except:
      refs:
        - master
  before_script:
  - date '+%Y-%m-%d %H:%M:%S %z'

  # Login to Docker Hub registry
  - echo "${DOCKERHUB_REGISTRY_PASSWORD}" | docker login -u "${DOCKERHUB_REGISTRY_USER}" --password-stdin

  # Login to GitLab registry
  - echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"

  script:
  - date '+%Y-%m-%d %H:%M:%S %z'

  - docker build
    -t "${DOCKERHUB_REGISTRY_USER}/${CI_PROJECT_NAME}:${VARIANT_TAG}"
    -t "${DOCKERHUB_REGISTRY_USER}/${CI_PROJECT_NAME}:${VARIANT_TAG_WITH_VERSION}"
    -t "${CI_REGISTRY_IMAGE}:${VARIANT_TAG}"
    -t "${CI_REGISTRY_IMAGE}:${VARIANT_TAG_WITH_VERSION}"
    "${VARIANT_BUILD_DIR}"

  - date '+%Y-%m-%d %H:%M:%S %z'

  # Push to Docker Hub registry. E.g. 'namespace/my-project:tag'
  - docker push "${DOCKERHUB_REGISTRY_USER}/${CI_PROJECT_NAME}:${VARIANT_TAG}"
  - docker push "${DOCKERHUB_REGISTRY_USER}/${CI_PROJECT_NAME}:${VARIANT_TAG_WITH_VERSION}"

  # Push to GitLab registry. E.g. 'registry.gitlab.com/namespace/my-project:tag
  - docker push "${CI_REGISTRY_IMAGE}:${VARIANT_TAG}"
  - docker push "${CI_REGISTRY_IMAGE}:${VARIANT_TAG_WITH_VERSION}"

  after_script:
  - date '+%Y-%m-%d %H:%M:%S %z'

  # Log out of Docker Hub registry
  - docker logout

  # Log out of GitLab registry
  - docker logout "${CI_REGISTRY}"

build-envsubst:
  <<: *build_definition
  variables:
    VARIANT_TAG: envsubst
    VARIANT_TAG_WITH_VERSION: envsubst-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/envsubst

build-git:
  <<: *build_definition
  variables:
    VARIANT_TAG: git
    VARIANT_TAG_WITH_VERSION: git-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/git

build-kustomize:
  <<: *build_definition
  variables:
    VARIANT_TAG: kustomize
    VARIANT_TAG_WITH_VERSION: kustomize-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/kustomize

build-jq:
  <<: *build_definition
  variables:
    VARIANT_TAG: jq
    VARIANT_TAG_WITH_VERSION: jq-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/jq

build-ssh:
  <<: *build_definition
  variables:
    VARIANT_TAG: ssh
    VARIANT_TAG_WITH_VERSION: ssh-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/ssh

build-envsubst-git:
  <<: *build_definition
  variables:
    VARIANT_TAG: envsubst-git
    VARIANT_TAG_WITH_VERSION: envsubst-git-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/envsubst-git

build-envsubst-git-kustomize:
  <<: *build_definition
  variables:
    VARIANT_TAG: envsubst-git-kustomize
    VARIANT_TAG_WITH_VERSION: envsubst-git-kustomize-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/envsubst-git-kustomize

build-envsubst-git-kustomize-jq:
  <<: *build_definition
  variables:
    VARIANT_TAG: envsubst-git-kustomize-jq
    VARIANT_TAG_WITH_VERSION: envsubst-git-kustomize-jq-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/envsubst-git-kustomize-jq

build-envsubst-git-kustomize-jq-ssh:
  <<: *build_definition
  variables:
    VARIANT_TAG: envsubst-git-kustomize-jq-ssh
    VARIANT_TAG_WITH_VERSION: envsubst-git-kustomize-jq-ssh-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/envsubst-git-kustomize-jq-ssh

build-envsubst-kustomize:
  <<: *build_definition
  variables:
    VARIANT_TAG: envsubst-kustomize
    VARIANT_TAG_WITH_VERSION: envsubst-kustomize-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/envsubst-kustomize

build-envsubst-kustomize-jq:
  <<: *build_definition
  variables:
    VARIANT_TAG: envsubst-kustomize-jq
    VARIANT_TAG_WITH_VERSION: envsubst-kustomize-jq-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/envsubst-kustomize-jq

build-envsubst-kustomize-jq-ssh:
  <<: *build_definition
  variables:
    VARIANT_TAG: envsubst-kustomize-jq-ssh
    VARIANT_TAG_WITH_VERSION: envsubst-kustomize-jq-ssh-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/envsubst-kustomize-jq-ssh

build-envsubst-jq:
  <<: *build_definition
  variables:
    VARIANT_TAG: envsubst-jq
    VARIANT_TAG_WITH_VERSION: envsubst-jq-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/envsubst-jq

build-envsubst-jq-ssh:
  <<: *build_definition
  variables:
    VARIANT_TAG: envsubst-jq-ssh
    VARIANT_TAG_WITH_VERSION: envsubst-jq-ssh-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/envsubst-jq-ssh

build-git-kustomize:
  <<: *build_definition
  variables:
    VARIANT_TAG: git-kustomize
    VARIANT_TAG_WITH_VERSION: git-kustomize-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/git-kustomize

build-git-kustomize-jq:
  <<: *build_definition
  variables:
    VARIANT_TAG: git-kustomize-jq
    VARIANT_TAG_WITH_VERSION: git-kustomize-jq-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/git-kustomize-jq

build-git-kustomize-jq-ssh:
  <<: *build_definition
  variables:
    VARIANT_TAG: git-kustomize-jq-ssh
    VARIANT_TAG_WITH_VERSION: git-kustomize-jq-ssh-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/git-kustomize-jq-ssh

build-git-jq:
  <<: *build_definition
  variables:
    VARIANT_TAG: git-jq
    VARIANT_TAG_WITH_VERSION: git-jq-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/git-jq

build-git-jq-ssh:
  <<: *build_definition
  variables:
    VARIANT_TAG: git-jq-ssh
    VARIANT_TAG_WITH_VERSION: git-jq-ssh-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/git-jq-ssh

build-git-ssh:
  <<: *build_definition
  variables:
    VARIANT_TAG: git-ssh
    VARIANT_TAG_WITH_VERSION: git-ssh-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/git-ssh

build-kustomize-jq:
  <<: *build_definition
  variables:
    VARIANT_TAG: kustomize-jq
    VARIANT_TAG_WITH_VERSION: kustomize-jq-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/kustomize-jq

build-kustomize-jq-ssh:
  <<: *build_definition
  variables:
    VARIANT_TAG: kustomize-jq-ssh
    VARIANT_TAG_WITH_VERSION: kustomize-jq-ssh-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/kustomize-jq-ssh

build-kustomize-ssh:
  <<: *build_definition
  variables:
    VARIANT_TAG: kustomize-ssh
    VARIANT_TAG_WITH_VERSION: kustomize-ssh-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/kustomize-ssh

build-jq-ssh:
  <<: *build_definition
  variables:
    VARIANT_TAG: jq-ssh
    VARIANT_TAG_WITH_VERSION: jq-ssh-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/jq-ssh
